# Generated by Django 5.1 on 2025-03-11 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assistant_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="preco_fixo_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="preco_hora_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tipo_usuario",
            field=models.CharField(
                choices=[("Administrador", "Administrador"), ("Usuario", "Usuario")],
                default="Usuario",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.TextField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="Assistant_app.chat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjetoHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                (
                    "tipo_pagamento",
                    models.CharField(
                        choices=[("Hora", "Hora"), ("Fixo", "Fixo")], max_length=10
                    ),
                ),
                ("valor_pagamento", models.FloatField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjetoHabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habilidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Assistant_app.habilidade",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habilidades",
                        to="Assistant_app.projetohistorico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespostaAssistente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.TextField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "mensagem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resposta_assistente",
                        to="Assistant_app.mensagem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioHabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habilidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Assistant_app.habilidade",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habilidades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
