# Generated by Django 5.1 on 2025-03-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Assistant_app",
            "0002_habilidade_user_preco_fixo_min_user_preco_hora_min_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="nome",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
