# Generated by Django 5.1 on 2025-03-20 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assistant_app", "0003_chat_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="projetohistorico",
            name="data",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
